training_config:
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 16
  num_train_epochs: 5
  dataloader_num_workers: 8
  fp16: true
  optim: "adamw_torch"
  learning_rate: 5.0e-5
  logging_steps: 10
  evaluation_strategy: "steps"
  save_strategy: "steps"
  eval_steps: 1
  save_steps: 500
  save_total_limit: 5
  deepspeed: ./configs/deepspeed/ds_config_zero1.json
  output_dir: /raid/moriy/model/heron/
  report_to: "wandb"

model_config:
  fp16: true
  # pretrained_path:
  model_type: git_llm
  language_model_name: facebook/opt-350m
  vision_model_name: openai/clip-vit-base-patch16
  num_image_with_embedding: 16 # 1 for image, otherwise for number of video sequences
  max_length: 256
  keys_to_finetune: []
  keys_to_freeze:
    - vision_model
    - language_model

  use_lora: false

dataset_config_path: 
  - ./configs/datasets/soccernet.yaml
